name: Joshlee
favicon: null
layout_spectrum: 0.3735758909024298
typography_spectrum: 0.3823604667559266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8722543395124376
  lightness: 0.793318607378751
  saturation: 0.2952976324595511
  rhythmicContrast: 0.020398573484271765
purpose: []
